### ISSUE TITLE
BT doesn't work on build

### ISSUE THREAD

**Issue by jerdog** [sonyxperiadev/device-sony-yuga#4]
Bluetooth doesn't work on build

```
D/BluetoothManagerService(  567): enable():  mBluetooth =android.bluetooth.IBluetooth$Stub$Proxy@40feee68 mBinding = false
D/BluetoothManagerService(  567): Message: 1
D/BluetoothManagerService(  567): MESSAGE_ENABLE: mBluetooth = android.bluetooth.IBluetooth$Stub$Proxy@40feee68
D/BluetoothAdapterService( 2195): Broadcasting updateAdapterState() to 1 receivers.
D/BluetoothBondStateMachine( 2195): make
D/BluetoothManagerService(  567): Message: 60
D/BluetoothManagerService(  567): MESSAGE_BLUETOOTH_STATE_CHANGE: prevState = 10, newState=11
D/BluetoothManagerService(  567): Bluetooth State Change Intent: 10 -> 11
D/BluetoothAdapterService(1089261376)( 2195): getState(): mAdapterProperties: com.android.bluetooth.btservice.AdapterProperties@40ece1a0
I/bluedroid( 2195): enable
D/BTIF_CORE( 2195): not disabled
E/BluetoothAdapterState( 2195): Error while turning Bluetooth On
D/BluetoothAdapterService( 2195): Broadcasting updateAdapterState() to 1 receivers.
D/BluetoothManagerService(  567): Message: 60
D/BluetoothManagerService(  567): MESSAGE_BLUETOOTH_STATE_CHANGE: prevState = 11, newState=10
D/BluetoothManagerService(  567): Broadcasting onBluetoothStateChange(false) to 7 receivers.
D/BluetoothHeadset( 1064): onBluetoothStateChange: up=false
E/BluetoothHeadset( 1064): 
E/BluetoothHeadset( 1064): java.lang.IllegalArgumentException: Service not registered: android.bluetooth.BluetoothHeadset$2@40f0aca0
E/BluetoothHeadset( 1064):  at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:921)
E/BluetoothHeadset( 1064):  at android.app.ContextImpl.unbindService(ContextImpl.java:1451)
E/BluetoothHeadset( 1064):  at android.content.ContextWrapper.unbindService(ContextWrapper.java:484)
E/BluetoothHeadset( 1064):  at android.bluetooth.BluetoothHeadset$1.onBluetoothStateChange(BluetoothHeadset.java:234)
E/BluetoothHeadset( 1064):  at android.bluetooth.IBluetoothStateChangeCallback$Stub.onTransact(IBluetoothStateChangeCallback.java:55)
E/BluetoothHeadset( 1064):  at android.os.Binder.execTransact(Binder.java:351)
E/BluetoothHeadset( 1064):  at dalvik.system.NativeStart.run(Native Method)
D/BluetoothInputDevice( 1086): onBluetoothStateChange: up=false
E/BluetoothInputDevice( 1086): 
E/BluetoothInputDevice( 1086): java.lang.IllegalArgumentException: Service not registered: android.bluetooth.BluetoothInputDevice$2@40ee1730
E/BluetoothInputDevice( 1086):  at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:921)
E/BluetoothInputDevice( 1086):  at android.app.ContextImpl.unbindService(ContextImpl.java:1451)
E/BluetoothInputDevice( 1086):  at android.content.ContextWrapper.unbindService(ContextWrapper.java:484)
E/BluetoothInputDevice( 1086):  at android.bluetooth.BluetoothInputDevice$1.onBluetoothStateChange(BluetoothInputDevice.java:199)
E/BluetoothInputDevice( 1086):  at android.bluetooth.IBluetoothStateChangeCallback$Stub.onTransact(IBluetoothStateChangeCallback.java:55)
E/BluetoothInputDevice( 1086):  at android.os.Binder.execTransact(Binder.java:351)
E/BluetoothInputDevice( 1086):  at dalvik.system.NativeStart.run(Native Method)
D/BluetoothPbap( 1086): onBluetoothStateChange: up=false
E/BluetoothPbap( 1086): 
E/BluetoothPbap( 1086): java.lang.IllegalArgumentException: Service not registered: android.bluetooth.BluetoothPbap$2@40eebdf0
E/BluetoothPbap( 1086):     at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:921)
E/BluetoothPbap( 1086):     at android.app.ContextImpl.unbindService(ContextImpl.java:1451)
E/BluetoothPbap( 1086):     at android.content.ContextWrapper.unbindService(ContextWrapper.java:484)
E/BluetoothPbap( 1086):     at android.bluetooth.BluetoothPbap$1.onBluetoothStateChange(BluetoothPbap.java:122)
E/BluetoothPbap( 1086):     at android.bluetooth.IBluetoothStateChangeCallback$Stub.onTransact(IBluetoothStateChangeCallback.java:55)
E/BluetoothPbap( 1086):     at android.os.Binder.execTransact(Binder.java:351)
E/BluetoothPbap( 1086):     at dalvik.system.NativeStart.run(Native Method)
D/BluetoothA2dp(  567): onBluetoothStateChange: up=false
E/BluetoothA2dp(  567): 
E/BluetoothA2dp(  567): java.lang.IllegalArgumentException: Service not registered: android.bluetooth.BluetoothA2dp$2@40efb6f0
E/BluetoothA2dp(  567):     at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:921)
E/BluetoothA2dp(  567):     at android.app.ContextImpl.unbindService(ContextImpl.java:1451)
E/BluetoothA2dp(  567):     at android.bluetooth.BluetoothA2dp$1.onBluetoothStateChange(BluetoothA2dp.java:121)
E/BluetoothA2dp(  567):     at com.android.server.BluetoothManagerService.sendBluetoothStateCallback(BluetoothManagerService.java:471)
E/BluetoothA2dp(  567):     at com.android.server.BluetoothManagerService.bluetoothStateChangeHandler(BluetoothManagerService.java:1049)
E/BluetoothA2dp(  567):     at com.android.server.BluetoothManagerService.access$2700(BluetoothManagerService.java:46)
E/BluetoothA2dp(  567):     at com.android.server.BluetoothManagerService$BluetoothHandler.handleMessage(BluetoothManagerService.java:814)
E/BluetoothA2dp(  567):     at android.os.Handler.dispatchMessage(Handler.java:99)
E/BluetoothA2dp(  567):     at android.os.Looper.loop(Looper.java:137)
E/BluetoothA2dp(  567):     at android.os.HandlerThread.run(HandlerThread.java:60)
D/BluetoothHeadset(  567): onBluetoothStateChange: up=false
E/BluetoothHeadset(  567): 
E/BluetoothHeadset(  567): java.lang.IllegalArgumentException: Service not registered: android.bluetooth.BluetoothHeadset$2@40f03870
E/BluetoothHeadset(  567):  at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:921)
E/BluetoothHeadset(  567):  at android.app.ContextImpl.unbindService(ContextImpl.java:1451)
E/BluetoothHeadset(  567):  at android.bluetooth.BluetoothHeadset$1.onBluetoothStateChange(BluetoothHeadset.java:234)
E/BluetoothHeadset(  567):  at com.android.server.BluetoothManagerService.sendBluetoothStateCallback(BluetoothManagerService.java:471)
E/BluetoothHeadset(  567):  at com.android.server.BluetoothManagerService.bluetoothStateChangeHandler(BluetoothManagerService.java:1049)
E/BluetoothHeadset(  567):  at com.android.server.BluetoothManagerService.access$2700(BluetoothManagerService.java:46)
E/BluetoothHeadset(  567):  at com.android.server.BluetoothManagerService$BluetoothHandler.handleMessage(BluetoothManagerService.java:814)
E/BluetoothHeadset(  567):  at android.os.Handler.dispatchMessage(Handler.java:99)
E/BluetoothHeadset(  567):  at android.os.Looper.loop(Looper.java:137)
E/BluetoothHeadset(  567):  at android.os.HandlerThread.run(HandlerThread.java:60)
E/BluetoothPan( 1086): 
E/BluetoothPan( 1086): java.lang.IllegalArgumentException: Service not registered: android.bluetooth.BluetoothPan$2@40ee6b70
E/BluetoothPan( 1086):  at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:921)
E/BluetoothPan( 1086):  at android.app.ContextImpl.unbindService(ContextImpl.java:1451)
E/BluetoothPan( 1086):  at android.content.ContextWrapper.unbindService(ContextWrapper.java:484)
E/BluetoothPan( 1086):  at android.bluetooth.BluetoothPan$1.onBluetoothStateChange(BluetoothPan.java:183)
E/BluetoothPan( 1086):  at android.bluetooth.IBluetoothStateChangeCallback$Stub.onTransact(IBluetoothStateChangeCallback.java:55)
E/BluetoothPan( 1086):  at android.os.Binder.execTransact(Binder.java:351)
E/BluetoothPan( 1086):  at dalvik.system.NativeStart.run(Native Method)
D/BluetoothHeadset( 1064): onBluetoothStateChange: up=false
E/BluetoothHeadset( 1064): 
E/BluetoothHeadset( 1064): java.lang.IllegalArgumentException: Service not registered: android.bluetooth.BluetoothHeadset$2@40eed0a0
E/BluetoothHeadset( 1064):  at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:921)
E/BluetoothHeadset( 1064):  at android.app.ContextImpl.unbindService(ContextImpl.java:1451)
E/BluetoothHeadset( 1064):  at android.content.ContextWrapper.unbindService(ContextWrapper.java:484)
E/BluetoothHeadset( 1064):  at android.bluetooth.BluetoothHeadset$1.onBluetoothStateChange(BluetoothHeadset.java:234)
E/BluetoothHeadset( 1064):  at android.bluetooth.IBluetoothStateChangeCallback$Stub.onTransact(IBluetoothStateChangeCallback.java:55)
E/BluetoothHeadset( 1064):  at android.os.Binder.execTransact(Binder.java:351)
E/BluetoothHeadset( 1064):  at dalvik.system.NativeStart.run(Native Method)
D/BluetoothManagerService(  567): Bluetooth State Change Intent: 11 -> 10
I/BluetoothBondStateMachine( 2195): StableState(): Entering Off State
D/BluetoothAdapterService(1089261376)( 2195): getState(): mAdapterProperties: com.android.bluetooth.btservice.AdapterProperties@40ece1a0
D/BluetoothAdapterService(1089261376)( 2195): getState(): mAdapterProperties: com.android.bluetooth.btservice.AdapterProperties@40ece1a0
D/BluetoothAdapterService(1089261376)( 2195): getState(): mAdapterProperties: com.android.bluetooth.btservice.AdapterProperties@40ece1a0
D/BluetoothAdapterService(1089261376)( 2195): getState(): mAdapterProperties: com.android.bluetooth.btservice.AdapterProperties@40ece1a0
D/BluetoothAdapterService(1089261376)( 2195): getState(): mAdapterProperties: com.android.bluetooth.btservice.AdapterProperties@40ece1a0
W/ContextImpl( 1086): Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1352 android.content.ContextWrapper.startService:450 android.content.ContextWrapper.startService:450 com.android.settings.bluetooth.DockEventReceiver.beginStartingService:134 com.android.settings.bluetooth.DockEventReceiver.onReceive:115 
D/DockEventReceiver( 1086): finishStartingService: stopping service
D/BluetoothAdapterService(1089261376)( 2195): getState(): mAdapterProperties: com.android.bluetooth.btservice.AdapterProperties@40ece1a0
```

**Comment by sonyxperiadev** [comment]
works, tested on kk_mr2 built using this guide
http://developer.sonymobile.com/knowledge-base/open-source/open-devices/aosp-build-instructions/how-to-build-aosp-kitkat-for-unlocked-xperia-devices/
